### ISSUE TITLE
Crash on clicking Home from the Navigation Drawer when I'm on the Home screen itself

### ISSUE THREAD

**Issue by bapspatil** [k0shk0sh/FastHub#1652]
**FastHub Version:**  4.6.5
**Android Version:**  Android Oreo 8.1 (API 27)
**Device Information:**  
- MANUFACTURER: Xiaomi  
- BRAND: Xiaomi  
- MODEL: Mi A1  
---

When I click on the Home item on the Navigation Drawer when I'm on the Home screen, it crashes. 

I know this isn't expected user behavior and it's redundant to click on the Home item when you're already on the Home screen, but app still crashes when it shouldn't.

**Comment by k0shk0sh** [comment]
Fixed with a release I just pushed. 
Its no longer needed ;

**Comment by k0shk0sh** [comment]
Owh wait, home....   I didn't realize that but actually removed the profile icon.

**Comment by kj415j45** [comment]
Issue still happened on Fasthub 4.6.6

Android Version: Mokee 60.1(Android 6.0.1)
Device: LG F460

**Comment by k0shk0sh** [comment]
My latest comment here states its not fixed, could you not click home while you are at home for the meantime?

**Comment by batzner** [comment]
On my phone, clicking home while being on home doesn't crash but simply closes the app like double pressing the back button would do.

Fasthub Version: 4.6.6
Android Version: 7.0
Device: Huawei P10 Lite (WAS-LX1A)
