### ISSUE TITLE
Won't mark notification as read

### ISSUE THREAD

**Issue by chamini2** [k0shk0sh/FastHub#704]
**App Version: 3.2.0**

**OS Version: 25**

**Model: LGE-Nexus 5X**

 I have the settings to __not__ mark as read notifications when I click on them. That way I can check them out and still have them when I reach a desktop version of GitHub.

The problem is that sometimes I want to mark a notification as read because I don't have to see it when I get to the desktop, so I press the ☑️ to mark it and it still won't get marked.

I'm guessing it happens because I have the settings set to not mark as read.

_Sent from my LGE Nexus 5X using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by k0shk0sh** [comment]
Good catch :) I already fixed that

**Comment by chamini2** [comment]
Will be available in the next release?

_Sent from my LGE Nexus 5X using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by k0shk0sh** [comment]
Definitely :)

**Comment by chamini2** [comment]
Closing then! 🙃

_Sent from my LGE Nexus 5X using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by k0shk0sh** [comment]
with a commit :p

**Comment by k0shk0sh** [comment]
the reason I want to close it with a commit, is because the changelog :D

**Comment by chamini2** [comment]
I thought you had already fixed it during the last week. I understand now.

_Sent from my LGE Nexus 5X using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by k0shk0sh** [comment]
I just fixed it :p

**Comment by chamini2** [comment]
I'm not sure I understand, there was no commit

**Comment by yakov116** [comment]
@chamini2 He will close the issue when he commits. (Prob. tomorrow morning)

Thanks for your feedback

**Comment by k0shk0sh** [comment]
@chamini2 haven't committed yet :p 

_Sent from my Samsung SM-G950F using [FastHub Debug](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by k0shk0sh** [comment]
this fixed with 54115508f5b9b0837de55430004b5bd9f9cef170

**Comment by CarsonF** [comment]
This is still a problem for me. I do have "disable notification read status" enabled.

App Version: 4.0.3
OS Version: 8.0.0
Model: Nexus 6P

**Comment by chamini2** [comment]
Yeah, this only works if I mark *all* notifications as read, not if I mark one by one.

**Comment by yakov116** [comment]
Not that it has to do with this (I have the same issue as above too)

But why do I get a notification for my own replys? 



_Sent from my Google Nexus 9 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by k0shk0sh** [comment]
@CarsonF this has been fixed

_Sent from my Samsung SM-G950F using [FastHub Debug](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
