### ISSUE TITLE
FastHub does not show submodule

### ISSUE THREAD

**Issue by iamsubhranil** [k0shk0sh/FastHub#753]
**FastHub Version:**  3.2.0

FastHub is unable to show submodule in my git repository. It is somehow showing the submodule as a file(not .gitmodules), with the information about the submodule repository, without showing the repository at the specific checkout itself. This is reproducible by going to [my repository](https://github.com/iamsubhranil/VisibilityCount/tree/pthread) and trying to view the submodule [C-Thread-Pool](https://github.com/iamsubhranil/C-Thread-Pool/tree/430251cb657f82c9a94d4ed72db6f5ea2e30f5d9).

**Android Version:**  7.1.1
**Device Information:**  Xiaomi Redmi 2 Prime

**Comment by k0shk0sh** [comment]
fixed in 7b89d1ecd266015cd0bfe5ed45cf5959e18e164d

**Comment by iamsubhranil** [comment]
Nicely done 👍
Just a few glitches. 
1. FastHub doesn't checkout the specific version of the submodule, it directly opens the master branch.
2. Icon still not fixed. Showing submodule as type file and size 0 bytes.
P. S. : Should I open a new issue?
P. S. 2 : (off topic) I liked the previous version of branch list more!

**Comment by k0shk0sh** [comment]
@iamsubhranil where Am I supposed to check for the branch? I only could use the URL to parse the branch and if there isn't any branch or ref in it, then master is opened.

For icon, is a bit tricky but surely doable. 

_Sent from my Samsung SM-G950F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by iamsubhranil** [comment]
Well you can use the json formatted submodule info file(which was previously being shown) to checkout at the specific commit of the repo. AFAIK, there was that version hash specified in the file. And GitHub always does that, i.e. checks out at the specific commit where the submodule stays in. Isn't there any API for it?

**Comment by k0shk0sh** [comment]
@iamsubhranil https://github.com/iamsubhranil/C-Thread-Pool/tree/430251cb657f82c9a94d4ed72db6f5ea2e30f5d9

This is actually the url, and about reading from somewhere, I don't I want to complex things up, trying to simplify the process, if there was a ref then I had used it. 

_Sent from my Samsung SM-G950F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
