### ISSUE TITLE
Wrong traditional chinese

### ISSUE THREAD

**Issue by ALiangLiang** [k0shk0sh/FastHub#757]
**App Version: 3.2.0**

**OS Version: 23**

**Model: asus-ASUS_Z00ED**

 I select Tradional Chinese. But it's Simplified Chinese, not Traditional chinese. 
![setting page](http://i.imgur.com/BRR6pUS.jpg)

**Comment by yakov116** [comment]
@ALiangLiang Can you update to 4.0.1 that was released about 10 min ago?

**Comment by k0shk0sh** [comment]
This has been fixed in 4.0.x

_Sent from my Samsung SM-G950F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by ALiangLiang** [comment]
No, still wrong. I update to latest 4.0.1.
![issue page](http://i.imgur.com/s7e0Orz.jpg)

![side part](http://i.imgur.com/Q0UUDNd.jpg)

![setting page](http://i.imgur.com/4631cSG.jpg)

**Comment by k0shk0sh** [comment]
@ALiangLiang please try and reselect it again. Switch to any other lang and select ur lang.

_Sent from my Samsung SM-G950F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by ALiangLiang** [comment]
@k0shk0sh um.....I already try. But not work. Even clear and reopen APP. Still display simplified chinses...

**Comment by k0shk0sh** [comment]
@ALiangLiang you mean you didn't choose the language? Was it configured by default? Or you can still change language to English? 

_Sent from my Samsung SM-G950F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by ALiangLiang** [comment]
@k0shk0sh I choose the "Tradional Chinese". But whole APP change to "Simplified Chinese".  BTW. I can change to English or any other language. But only traditional chinese is not true traditional

**Comment by ALiangLiang** [comment]
#658 Old bug.
![image](https://user-images.githubusercontent.com/6974496/28249792-0f3b505a-6a8f-11e7-91c7-36b14493316b.png)

**Comment by k0shk0sh** [comment]
@ALiangLiang hmmm, can't really get it, looking at log, the selected lang is traditional and the OS should take the traditional locales, could you please at the file and confirm if the strings are translated into traditional? 

_Sent from my Samsung SM-G950F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by ALiangLiang** [comment]
@k0shk0sh 
In arrays.xml, it's named "zh-rCN". But in res folder, really simplified chinese(zh-CN) is  in "values-zh" not "values-zh-rCN".
Im not sure is it cause yhis problem.

https://github.com/k0shk0sh/FastHub/blob/master/app/src/main/res/values/arrays.xml#137

![wrong folder name?](http://i.imgur.com/BWcmG1S.jpg)

**Comment by k0shk0sh** [comment]
@ALiangLiang good point, let me try it out.

_Sent from my Samsung SM-G950F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by ALiangLiang** [comment]
I also mapping the sidebar string between simplified and traditional. 
Simplified(zh-rCN) Traditional(zh-rTW) stringID
主页 首頁 home
概况 個人檔案 profile
组织 組織 organization
通知 通知 notifications (same chars)
书签 釘選 pin
趋势 趨勢 trending
设置 設定 setting
关于 關於 ablout

![zh-CN sidebar](https://camo.githubusercontent.com/d54f59011fc0458273b6951d5c2246efe5e940a1/687474703a2f2f692e696d6775722e636f6d2f51305555444e642e6a7067)

**Comment by k0shk0sh** [comment]
This is how I fixed that 😖 

```
if (language.equalsIgnoreCase("zh-rCN")) {
    locale = Locale.SIMPLIFIED_CHINESE;
} else if (language.equalsIgnoreCase("zh-rTW")) {
    locale = Locale.TRADITIONAL_CHINESE;
}
```

since I couldn't really understand why Android doesn't take  even tho the debug says the locale value is `zh-rTW`.
